# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53a7ec9414d75b1ec951351c172995d388ba8ca2ccabb46fcc4fc02b30669150c87ec9668292a2a3e9dc6b0254a94fc02c025c60092b42d3a0d4fe19fc9af487

test:
  secret_key_base: 5790aca53a43757e6fb112742d4deb6d78a9903cdbf09ad04d42b2a79478f42e4c7b94b7310e7b9987ee1713833bfe9ce9ed4ff1fb6054cd2b6ba22b780e65eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
